Sidecar
hcholab/sfkit pull request #32
Opened 2024-03-27 20:38 UTC by simonjmendelsohn

2024-04-01 21:37 UTC, dinvlad requested changes

2024-04-01 21:37 UTC, dinvlad commented on sfkit/sidecar/server.py
> +                    process.wait()
```suggestion
                    while True:
                        line = process.stdout.readline().strip()
                        if line:
                            client.sendall(line.encode("utf-8"))
                            print(line)
                        elif process.poll() is not None:
                            break
```
Simplifying, thanks to combined stderr/stdout above.

2024-04-01 21:37 UTC, dinvlad commented on sfkit/sidecar/server.py
> +            data_path = request.get("data_path", "")
```suggestion
            data_path = os.path.realpath(request.get("data_path", ""))
            
            if not data_path.startswith(constants.SAFE_DATA_PATH):
                client.sendall("Invalid data_path".encode("utf-8"))
                client.close()
                return
```
This avoids a possible path traversal attack.. We should also pair this with
```py
# constants.py

SAFE_DATA_PATH = os.environ.get("SAFE_DATA_PATH", "/data")
SAFE_DATA_PATH = os.path.join(os.path.realpath(SAFE_DATA_PATH), "")
```
(`SAFE_DATA_PATH` env var will be set to `/home/jupyter` when running as a Leo VM container)

`realpath` here resolves any symbolic links (if present), and `join` with `""` ensures there's a trailing slash, which is important to reject user-defined paths like `/home/jupyter2` later.

2024-04-01 21:37 UTC, dinvlad commented on sfkit/sidecar/server.py
> +                command.extend(["--data_path", data_path])
```suggestion
            command.extend(["--data_path", data_path])
```

2024-04-02 17:51 UTC, dinvlad commented on sfkit/sidecar/server.py
> +                client.sendall("Invalid data_path".encode("utf-8"))
```suggestion
                client.sendall(f"data_path should start with {constants.SAFE_DATA_PATH}".encode("utf-8"))
```
Might be good to give them feedback on what to expect

2024-04-02 19:33 UTC, dinvlad approved these changes

2024-04-02 19:34 UTC, zbedo approved these changes

2024-04-02 19:57 UTC, merged